services:
  postgres:
    image: postgres:16-alpine
    container_name: assignment2-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: assignment2-api
    ports:
      - "4080:4000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydb
      NODE_ENV: production
      PORT: 4000
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assignment2-frontend
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://3.81.151.8:4080
      NODE_ENV: production
    depends_on:
      - api

volumes:
  postgres_data: